export const ORDER_SET_TYPE = "ORDER_SET_TYPE";

export const CATEGORY_LIST_REQUEST = "CATEGORY_LIST_REQUEST";
export const CATEGORY_LIST_FAIL = "CATEGORY_LIST_FAIL";
export const CATEGORY_LIST_SUCCESS = "CATEGORY_LIST_SUCCESS";

export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";

export const ORDER_ADD_ITEM = "ORDER_ADD_ITEM";
export const ORDER_REMOVE_ITEM = "ORDER_REMOVE_ITEM";
export const CLEAR_ORDER = "CLEAR_ORDER";

export const ORDER_SET_PAYMENT_TYPE = "ORDER_SET_PAYMENT_TYPE";

export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const SET_ORDERITEMS = "SET_ORDERITEMS";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const QUEUE_LIST_REQUEST = "QUEUE_LIST_REQUEST";
export const QUEUE_LIST_SUCCESS = "QUEUE_LIST_SUCCESS";
export const QUEUE_LIST_FAIL = "QUEUE_LIST_FAIL";

export const SCREEN_SET_WIDTH = "SCREEN_SET_WIDTH";
